### ISSUE TITLE
Add helper function extractHashtags

### ISSUE THREAD

**Issue by Moemen-Gaballah** [piscibus/php-hashtag#5]
### Description

add helper function "extractHashtags($text)". it's easy to use instead of use static method

### Example

$text = 'This is an #English #text with #hashtags';

$hashtags = Extractor::extract($text); // ['English', 'text', 'hashtags']

// OR use helper function
    
$hashtags =  extractHashtags($text); // ['English', 'text', 'hashtags']

**Comment by imdhemy** [comment]
Closed by #7
